modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cenchants"
version = "${version}"
displayName = "Combat Enchantments"
authors = "dsfhdshdjtsb"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.cenchants]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cenchants]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cenchants]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"